2024-11-15 03:13:54,819 INFO [root] [driver_utils.py:get_driver:15] - creat chrome driver
2024-11-15 03:13:55,606 WARNING [selenium.webdriver.common.selenium_manager] [selenium_manager.py:_process_logs:138] - Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
2024-11-15 03:13:57,785 INFO [root] [test_1login.py:test_login:28] - login with 15249205917--123456--8888
2024-11-15 03:13:57,978 INFO [root] [test_1login.py:test_login:34] - wait 5s for page display
2024-11-15 03:14:05,982 INFO [root] [driver_utils.py:quit_driver:31] - chrome driver is still alive
2024-11-15 03:14:05,985 INFO [root] [driver_utils.py:get_driver:20] - use existed chrome driver
2024-11-15 03:14:06,229 INFO [root] [test_cart.py:test_cart:26] - search with 小米手机5
2024-11-15 03:14:10,953 INFO [root] [driver_utils.py:quit_driver:31] - chrome driver is still alive
2024-11-15 03:14:10,956 INFO [root] [driver_utils.py:get_driver:20] - use existed chrome driver
2024-11-15 03:14:18,935 INFO [root] [driver_utils.py:quit_driver:31] - chrome driver is still alive
2024-11-15 03:14:18,939 INFO [root] [driver_utils.py:get_driver:20] - use existed chrome driver
2024-11-15 03:14:23,013 WARNING [urllib3.connectionpool] [connectionpool.py:urlopen:870] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002265173DB20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52be1ec16052f37d8bd6b8e1aef00349/url
2024-11-15 03:14:27,087 WARNING [urllib3.connectionpool] [connectionpool.py:urlopen:870] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002265173E5D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52be1ec16052f37d8bd6b8e1aef00349/url
2024-11-15 03:14:31,157 WARNING [urllib3.connectionpool] [connectionpool.py:urlopen:870] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002265173F050>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52be1ec16052f37d8bd6b8e1aef00349/url
2024-11-15 03:14:35,376 INFO [root] [driver_utils.py:get_driver:20] - use existed chrome driver
2024-11-15 03:14:39,447 WARNING [urllib3.connectionpool] [connectionpool.py:urlopen:870] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022651367290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52be1ec16052f37d8bd6b8e1aef00349/screenshot
2024-11-15 03:14:43,528 WARNING [urllib3.connectionpool] [connectionpool.py:urlopen:870] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000226513667E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52be1ec16052f37d8bd6b8e1aef00349/screenshot
2024-11-15 03:14:47,604 WARNING [urllib3.connectionpool] [connectionpool.py:urlopen:870] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022651366F30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52be1ec16052f37d8bd6b8e1aef00349/screenshot
2024-11-15 03:15:02,294 INFO [root] [driver_utils.py:get_driver:15] - creat chrome driver
2024-11-15 03:15:03,037 WARNING [selenium.webdriver.common.selenium_manager] [selenium_manager.py:_process_logs:138] - Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
2024-11-15 03:15:05,283 INFO [root] [test_1login.py:test_login:28] - login with 15249205917--123456--8888
2024-11-15 03:15:05,488 INFO [root] [test_1login.py:test_login:34] - wait 5s for page display
2024-11-15 03:15:13,493 INFO [root] [driver_utils.py:quit_driver:31] - chrome driver is still alive
2024-11-15 03:15:13,495 INFO [root] [driver_utils.py:get_driver:20] - use existed chrome driver
2024-11-15 03:15:13,760 INFO [root] [test_cart.py:test_cart:26] - search with 小米手机5
2024-11-15 03:15:19,195 INFO [root] [test_cart.py:test_cart:30] - wait 5s for page display
2024-11-15 03:15:22,234 INFO [root] [driver_utils.py:quit_driver:31] - chrome driver is still alive
2024-11-15 03:15:22,236 INFO [root] [driver_utils.py:get_driver:20] - use existed chrome driver
2024-11-15 03:15:38,670 INFO [root] [driver_utils.py:quit_driver:31] - chrome driver is still alive
2024-11-15 03:15:38,672 INFO [root] [driver_utils.py:get_driver:20] - use existed chrome driver
2024-11-15 03:15:47,593 INFO [root] [driver_utils.py:quit_driver:31] - chrome driver is still alive
2024-11-15 03:15:47,594 INFO [root] [driver_utils.py:get_driver:20] - use existed chrome driver
2024-11-15 03:15:47,674 INFO [root] [driver_utils.py:quit_driver:27] - quit chrome driver
